Repository valory-xyz/open-autonomy, pull requests merged in 2022-10, with the labels that each got.

#1436 Remove unused dependencies
  .github/workflows/main_workflow.yml
  Pipfile
  setup.cfg
  tox.ini
Labels: refactor

#1435 Extract liquidity rebalancing
  .github/workflows/main_workflow.yml
  Makefile
  Pipfile
  docs/package_list.md
  packages/packages.json
  packages/valory/contracts/uniswap_v2_erc20/__init__.py
  packages/valory/contracts/uniswap_v2_erc20/build/IUniswapV2ERC20.json
  packages/valory/contracts/uniswap_v2_erc20/contract.py
  packages/valory/contracts/uniswap_v2_erc20/contract.yaml
  packages/valory/contracts/uniswap_v2_erc20/tests/__init__.py
  packages/valory/contracts/uniswap_v2_erc20/tests/test_contract.py
  packages/valory/contracts/uniswap_v2_router_02/__init__.py
  packages/valory/contracts/uniswap_v2_router_02/build/IUniswapV2Router02.json
  packages/valory/contracts/uniswap_v2_router_02/contract.py
  packages/valory/contracts/uniswap_v2_router_02/contract.yaml
  packages/valory/contracts/uniswap_v2_router_02/tests/__init__.py
  packages/valory/contracts/uniswap_v2_router_02/tests/test_contract.py
  packages/valory/skills/liquidity_provision_abci/README.md
  packages/valory/skills/liquidity_provision_abci/__init__.py
  packages/valory/skills/liquidity_provision_abci/behaviours.py
  packages/valory/skills/liquidity_provision_abci/composition.py
  packages/valory/skills/liquidity_provision_abci/dialogues.py
  packages/valory/skills/liquidity_provision_abci/fsm_specification.yaml
  packages/valory/skills/liquidity_provision_abci/handlers.py
  packages/valory/skills/liquidity_provision_abci/models.py
  packages/valory/skills/liquidity_provision_abci/skill.yaml
  packages/valory/skills/liquidity_provision_abci/tests/__init__.py
  packages/valory/skills/liquidity_provision_abci/tests/conftest.py
  packages/valory/skills/liquidity_provision_abci/tests/test_behaviours.py
  packages/valory/skills/liquidity_provision_abci/tests/test_dialogues.py
  packages/valory/skills/liquidity_provision_abci/tests/test_handlers.py
  packages/valory/skills/liquidity_provision_abci/tests/test_integration.py
  packages/valory/skills/liquidity_provision_abci/tests/test_models.py
  packages/valory/skills/liquidity_rebalancing_abci/README.md
  packages/valory/skills/liquidity_rebalancing_abci/__init__.py
  packages/valory/skills/liquidity_rebalancing_abci/behaviours.py
  packages/valory/skills/liquidity_rebalancing_abci/dialogues.py
  packages/valory/skills/liquidity_rebalancing_abci/fsm_specification.yaml
  packages/valory/skills/liquidity_rebalancing_abci/handlers.py
  packages/valory/skills/liquidity_rebalancing_abci/models.py
  packages/valory/skills/liquidity_rebalancing_abci/payloads.py
  packages/valory/skills/liquidity_rebalancing_abci/rounds.py
  packages/valory/skills/liquidity_rebalancing_abci/skill.yaml
  packages/valory/skills/liquidity_rebalancing_abci/test_tools/__init__.py
  packages/valory/skills/liquidity_rebalancing_abci/test_tools/integration.py
  packages/valory/skills/liquidity_rebalancing_abci/tests/__init__.py
  packages/valory/skills/liquidity_rebalancing_abci/tests/test_behaviours.py
  packages/valory/skills/liquidity_rebalancing_abci/tests/test_dialogues.py
  packages/valory/skills/liquidity_rebalancing_abci/tests/test_handlers.py
  packages/valory/skills/liquidity_rebalancing_abci/tests/test_models.py
  packages/valory/skills/liquidity_rebalancing_abci/tests/test_payloads.py
  packages/valory/skills/liquidity_rebalancing_abci/tests/test_rounds.py
  setup.cfg
  tox.ini
Labels: refactor

#1443 Fix tests for oracle extraction
  Makefile
  docs/demos/simple_abci.md
  docs/package_list.md
  packages/packages.json
  packages/valory/agents/register_reset/aea-config.yaml
  packages/valory/agents/registration_start_up/aea-config.yaml
  packages/valory/agents/simple_abci/aea-config.yaml
  packages/valory/services/register_reset/service.yaml
  packages/valory/services/simple_abci/service.yaml
  packages/valory/skills/register_reset_abci/README.md
  packages/valory/skills/register_reset_abci/skill.yaml
  scripts/generate_api_documentation.py
  tests/test_autonomy/base.py
  tests/test_autonomy/test_cli/test_fetch.py
  tests/test_autonomy/test_configurations.py
  tests/test_autonomy/test_replay.py
  tests/test_docs/test_code_blocks.py
Labels: test, refactor

#1478 Fully cover `common.py` in `abstract_round_abci`
  autonomy/constants.py
  docs/api/skills/abstract_round_abci/common.md
  docs/demos/hello_world_demo.md
  docs/demos/simple_abci.md
  docs/guides/quick_start.md
  docs/package_list.md
  packages/packages.json
  packages/valory/agents/hello_world/aea-config.yaml
  packages/valory/agents/register_reset/aea-config.yaml
  packages/valory/agents/registration_start_up/aea-config.yaml
  packages/valory/agents/simple_abci/aea-config.yaml
  packages/valory/agents/test_abci/aea-config.yaml
  packages/valory/services/hello_world/service.yaml
  packages/valory/services/register_reset/service.yaml
  packages/valory/services/simple_abci/service.yaml
  packages/valory/skills/abstract_round_abci/common.py
  packages/valory/skills/abstract_round_abci/skill.yaml
  packages/valory/skills/abstract_round_abci/tests/test_common.py
  packages/valory/skills/hello_world_abci/skill.yaml
  packages/valory/skills/register_reset_abci/skill.yaml
  packages/valory/skills/registration_abci/skill.yaml
  packages/valory/skills/reset_pause_abci/skill.yaml
  packages/valory/skills/safe_deployment_abci/skill.yaml
  packages/valory/skills/simple_abci/skill.yaml
  packages/valory/skills/test_abci/skill.yaml
  packages/valory/skills/transaction_settlement_abci/skill.yaml
Labels: test

#1482 [0.3.4]: Remove superfluous test
  autonomy/constants.py
  docs/demos/hello_world_demo.md
  docs/demos/simple_abci.md
  docs/guides/quick_start.md
  docs/package_list.md
  packages/packages.json
  packages/valory/agents/hello_world/aea-config.yaml
  packages/valory/agents/register_reset/aea-config.yaml
  packages/valory/agents/registration_start_up/aea-config.yaml
  packages/valory/agents/simple_abci/aea-config.yaml
  packages/valory/agents/test_abci/aea-config.yaml
  packages/valory/services/hello_world/service.yaml
  packages/valory/services/register_reset/service.yaml
  packages/valory/services/simple_abci/service.yaml
  packages/valory/skills/abstract_round_abci/skill.yaml
  packages/valory/skills/abstract_round_abci/tests/test_common.py
  packages/valory/skills/hello_world_abci/skill.yaml
  packages/valory/skills/register_reset_abci/skill.yaml
  packages/valory/skills/registration_abci/skill.yaml
  packages/valory/skills/reset_pause_abci/skill.yaml
  packages/valory/skills/safe_deployment_abci/skill.yaml
  packages/valory/skills/simple_abci/skill.yaml
  packages/valory/skills/test_abci/skill.yaml
  packages/valory/skills/transaction_settlement_abci/skill.yaml
Labels: chore

#1481 [0.3.4]: chore: split round and payloads into separate files
  packages/valory/skills/termination_abci/behaviours.py
  packages/valory/skills/termination_abci/models.py
  packages/valory/skills/termination_abci/payloads.py
  packages/valory/skills/termination_abci/rounds.py
Labels: chore

#1484 [0.3.4]: Test/termination abstract_round abci
  autonomy/constants.py
  docs/api/skills/abstract_round_abci/base.md
  docs/api/skills/abstract_round_abci/behaviours.md
  docs/api/skills/abstract_round_abci/test_tools/abci_app.md
  docs/demos/hello_world_demo.md
  docs/demos/simple_abci.md
  docs/guides/quick_start.md
  docs/key_concepts/abci_app_class.md
  docs/package_list.md
  packages/packages.json
  packages/valory/agents/hello_world/aea-config.yaml
  packages/valory/agents/register_reset/aea-config.yaml
  packages/valory/agents/registration_start_up/aea-config.yaml
  packages/valory/agents/simple_abci/aea-config.yaml
  packages/valory/agents/test_abci/aea-config.yaml
  packages/valory/services/hello_world/service.yaml
  packages/valory/services/register_reset/service.yaml
  packages/valory/services/simple_abci/service.yaml
  packages/valory/skills/abstract_round_abci/base.py
  packages/valory/skills/abstract_round_abci/behaviours.py
  packages/valory/skills/abstract_round_abci/skill.yaml
  packages/valory/skills/abstract_round_abci/test_tools/abci_app.py
  packages/valory/skills/abstract_round_abci/tests/test_base.py
  packages/valory/skills/abstract_round_abci/tests/test_behaviours.py
  packages/valory/skills/hello_world_abci/skill.yaml
  packages/valory/skills/register_reset_abci/skill.yaml
  packages/valory/skills/registration_abci/skill.yaml
  packages/valory/skills/reset_pause_abci/skill.yaml
  packages/valory/skills/safe_deployment_abci/skill.yaml
  packages/valory/skills/simple_abci/skill.yaml
  packages/valory/skills/termination_abci/behaviours.py
  packages/valory/skills/termination_abci/handlers.py
  packages/valory/skills/termination_abci/models.py
  packages/valory/skills/termination_abci/payloads.py
  packages/valory/skills/termination_abci/rounds.py
  packages/valory/skills/termination_abci/skill.yaml
  packages/valory/skills/test_abci/skill.yaml
  packages/valory/skills/transaction_settlement_abci/skill.yaml
Labels: test
