Repository valory-xyz/open-autonomy, pull requests merged in 2024-10, with the labels that each got.

#2265 Fix: Add a small hash id in build_dir
  .gitignore
  Makefile
  autonomy/cli/deploy.py
  autonomy/cli/helpers/deployment.py
  autonomy/cli/replay.py
  autonomy/constants.py
  docs/advanced_reference/commands/autonomy_analyse.md
  docs/advanced_reference/commands/autonomy_deploy.md
  docs/advanced_reference/developer_tooling/benchmarking.md
  docs/advanced_reference/developer_tooling/debugging_in_the_cluster.md
  docs/advanced_reference/developer_tooling/dev_mode.md
  docs/api/cli/helpers/deployment.md
  docs/api/cli/replay.md
  docs/application_deployment.md
  docs/counter_example.md
  docs/guides/deploy_service.md
  docs/guides/quick_start.md
  tests/test_autonomy/test_cli/test_deploy/test_build/test_deployment.py
  tests/test_autonomy/test_cli/test_deploy/test_from_token.py
  tests/test_autonomy/test_cli/test_replay/test_agent.py
  tests/test_autonomy/test_cli/test_replay/test_tendermint.py
Labels: cli, open-autonomy, fix

#2266 Chore: Deprecate Görli chain
  autonomy/chain/config.py
  autonomy/chain/constants.py
  autonomy/cli/helpers/chain.py
  docs/advanced_reference/commands/autonomy_analyse.md
  docs/advanced_reference/commands/autonomy_deploy.md
  docs/advanced_reference/commands/autonomy_mint.md
  docs/advanced_reference/commands/autonomy_service.md
  docs/configure_service/configure_access_external_chains.md
  docs/guides/deploy_service.md
  scripts/whitelist.py
  tests/test_autonomy/test_cli/test_helpers/test_chain_helpers.py
Labels: chore

#2268 Release `v0.17.0`
  HISTORY.md
  autonomy/__version__.py
  autonomy/cli/helpers/fsm_spec.py
  autonomy/constants.py
  deployments/Dockerfiles/autonomy-user/requirements.txt
  docs/counter_example.md
  docs/guides/overview_of_the_development_process.md
  docs/package_list.md
  docs/upgrading.md
  packages/packages.json
  packages/valory/agents/abstract_abci/aea-config.yaml
  packages/valory/agents/counter/aea-config.yaml
  packages/valory/agents/offend_slash/aea-config.yaml
  packages/valory/agents/register_reset/aea-config.yaml
  packages/valory/agents/register_reset_recovery/aea-config.yaml
  packages/valory/agents/register_termination/aea-config.yaml
  packages/valory/agents/registration_start_up/aea-config.yaml
  packages/valory/agents/solana_transfer_agent/aea-config.yaml
  packages/valory/agents/test_abci/aea-config.yaml
  packages/valory/agents/test_ipfs/aea-config.yaml
  packages/valory/connections/abci/connection.yaml
  packages/valory/contracts/gnosis_safe/contract.yaml
  packages/valory/contracts/gnosis_safe_proxy_factory/contract.yaml
  packages/valory/contracts/service_registry/contract.yaml
  packages/valory/services/counter/service.yaml
  packages/valory/services/register_reset/service.yaml
  packages/valory/skills/abstract_abci/skill.yaml
  packages/valory/skills/abstract_round_abci/skill.yaml
  packages/valory/skills/counter/skill.yaml
  packages/valory/skills/offend_abci/skill.yaml
  packages/valory/skills/offend_slash_abci/skill.yaml
  packages/valory/skills/register_reset_abci/skill.yaml
  packages/valory/skills/register_reset_recovery_abci/skill.yaml
  packages/valory/skills/register_termination_abci/skill.yaml
  packages/valory/skills/registration_abci/skill.yaml
  packages/valory/skills/reset_pause_abci/skill.yaml
  packages/valory/skills/slashing_abci/skill.yaml
  packages/valory/skills/squads_transaction_settlement_abci/skill.yaml
  packages/valory/skills/termination_abci/skill.yaml
  packages/valory/skills/test_abci/skill.yaml
  packages/valory/skills/test_ipfs_abci/skill.yaml
  packages/valory/skills/test_solana_tx_abci/skill.yaml
  packages/valory/skills/transaction_settlement_abci/skill.yaml
  plugins/aea-test-autonomy/aea_test_autonomy/configurations.py
  plugins/aea-test-autonomy/setup.py
  tests/test_autonomy/test_cli/test_analyse/test_specs.py
  tests/test_autonomy/test_cli/test_scaffold_fsm.py
  tests/test_base.py
Labels: release

#2270 Implement dictionary overrides
  autonomy/deploy/base.py
  autonomy/deploy/generators/docker_compose/base.py
  autonomy/deploy/generators/docker_compose/templates.py
  deployments/Dockerfiles/autonomy/scripts/install.sh
  docs/api/deploy/generators/docker_compose/base.md
Labels: enhancement

#2271 Release `v0.18.0`
  HISTORY.md
  Pipfile
  autonomy/__version__.py
  autonomy/constants.py
  deployments/Dockerfiles/autonomy-user/requirements.txt
  docs/advanced_reference/commands/autonomy_build-image.md
  docs/counter_example.md
  docs/guides/define_agent.md
  docs/guides/overview_of_the_development_process.md
  docs/package_list.md
  docs/upgrading.md
  packages/packages.json
  packages/valory/agents/abstract_abci/aea-config.yaml
  packages/valory/agents/counter/aea-config.yaml
  packages/valory/agents/counter_client/aea-config.yaml
  packages/valory/agents/offend_slash/aea-config.yaml
  packages/valory/agents/register_reset/aea-config.yaml
  packages/valory/agents/register_reset_recovery/aea-config.yaml
  packages/valory/agents/register_termination/aea-config.yaml
  packages/valory/agents/registration_start_up/aea-config.yaml
  packages/valory/agents/solana_transfer_agent/aea-config.yaml
  packages/valory/agents/test_abci/aea-config.yaml
  packages/valory/agents/test_ipfs/aea-config.yaml
  packages/valory/connections/abci/connection.yaml
  packages/valory/connections/ipfs/connection.yaml
  packages/valory/contracts/gnosis_safe/contract.yaml
  packages/valory/contracts/gnosis_safe_proxy_factory/contract.yaml
  packages/valory/contracts/multicall2/contract.yaml
  packages/valory/contracts/service_registry/contract.yaml
  packages/valory/contracts/squads_multisig/contract.yaml
  packages/valory/services/counter/service.yaml
  packages/valory/services/register_reset/service.yaml
  packages/valory/skills/abstract_abci/skill.yaml
  packages/valory/skills/abstract_round_abci/skill.yaml
  packages/valory/skills/counter/skill.yaml
  packages/valory/skills/offend_abci/skill.yaml
  packages/valory/skills/offend_slash_abci/skill.yaml
  packages/valory/skills/register_reset_abci/skill.yaml
  packages/valory/skills/register_reset_recovery_abci/skill.yaml
  packages/valory/skills/register_termination_abci/skill.yaml
  packages/valory/skills/registration_abci/skill.yaml
  packages/valory/skills/reset_pause_abci/skill.yaml
  packages/valory/skills/slashing_abci/skill.yaml
  packages/valory/skills/squads_transaction_settlement_abci/skill.yaml
  packages/valory/skills/termination_abci/skill.yaml
  packages/valory/skills/test_abci/skill.yaml
  packages/valory/skills/test_ipfs_abci/skill.yaml
  packages/valory/skills/test_solana_tx_abci/skill.yaml
  packages/valory/skills/transaction_settlement_abci/skill.yaml
  plugins/aea-test-autonomy/aea_test_autonomy/configurations.py
  plugins/aea-test-autonomy/setup.py
  setup.py
  skaffold.yaml
  tests/test_base.py
  tox.ini
Labels: release

#2274 Release `v0.18.1`
  HISTORY.md
  autonomy/__version__.py
  autonomy/constants.py
  deployments/Dockerfiles/autonomy-user/requirements.txt
  docs/counter_example.md
  docs/guides/overview_of_the_development_process.md
  docs/package_list.md
  docs/upgrading.md
  packages/packages.json
  packages/valory/agents/abstract_abci/aea-config.yaml
  packages/valory/agents/counter/aea-config.yaml
  packages/valory/agents/offend_slash/aea-config.yaml
  packages/valory/agents/register_reset/aea-config.yaml
  packages/valory/agents/register_reset_recovery/aea-config.yaml
  packages/valory/agents/register_termination/aea-config.yaml
  packages/valory/agents/registration_start_up/aea-config.yaml
  packages/valory/agents/solana_transfer_agent/aea-config.yaml
  packages/valory/agents/test_abci/aea-config.yaml
  packages/valory/agents/test_ipfs/aea-config.yaml
  packages/valory/connections/abci/connection.yaml
  packages/valory/contracts/gnosis_safe/contract.yaml
  packages/valory/contracts/gnosis_safe_proxy_factory/contract.yaml
  packages/valory/contracts/service_registry/contract.yaml
  packages/valory/services/counter/service.yaml
  packages/valory/services/register_reset/service.yaml
  packages/valory/skills/abstract_abci/skill.yaml
  packages/valory/skills/abstract_round_abci/skill.yaml
  packages/valory/skills/counter/skill.yaml
  packages/valory/skills/offend_abci/skill.yaml
  packages/valory/skills/offend_slash_abci/skill.yaml
  packages/valory/skills/register_reset_abci/skill.yaml
  packages/valory/skills/register_reset_recovery_abci/skill.yaml
  packages/valory/skills/register_termination_abci/skill.yaml
  packages/valory/skills/registration_abci/skill.yaml
  packages/valory/skills/reset_pause_abci/skill.yaml
  packages/valory/skills/slashing_abci/skill.yaml
  packages/valory/skills/squads_transaction_settlement_abci/skill.yaml
  packages/valory/skills/termination_abci/skill.yaml
  packages/valory/skills/test_abci/skill.yaml
  packages/valory/skills/test_ipfs_abci/skill.yaml
  packages/valory/skills/test_solana_tx_abci/skill.yaml
  packages/valory/skills/transaction_settlement_abci/skill.yaml
  plugins/aea-test-autonomy/aea_test_autonomy/configurations.py
  plugins/aea-test-autonomy/setup.py
  tests/test_base.py
Labels: release
